name: exosky_tango
description: Una aplicación para explorar exoplanetas y visualizar cielos estelares.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11
  screenshot: ^3.0.0
  share_plus: ^10.0.2
  vector_math: ^2.1.2
  logging: ^1.0.2
  fl_chart: ^0.69.0
  xml: ^6.3.0
  csv: ^5.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
